### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by renecotyfanboy** [HEACIT/curated-test-data#4]
Hi everyone, is there any plan to maintain this data with new OGIP files ? I would be glad to contribute with my owns

**Comment by hamogu** [comment]
Thanks for reaching out!

The plan is to maintain this repository, so that it's available for all. Right now, each spectral fitting code (SPEC, XSPEC, Sherpa, BAX, ...) maintains their own set of files for testing. That seems to be a a lot of duplicated work. To goal of this repro is to reduce that overhead by hoping that everyone contributes here instead. Unfortunately, this repro have not gained a lot of traction; but once there is a sufficient number of files in here to make it useful, we'll make releases and make them available for download on HEASARC.

So, yes, we'd very much welcome your contributions! Since the goal is to use this in testing and continuous integration, we're aiming for small files where possible, for example we don't need several Chandra ACIS ARFS and RMFs since they all have the same format, or for XMM, we can have one of the RGS but don't necessarily both to keep the file size of the repro manageable. 

Just open a PR or ask here if anything is unclear.

**Comment by renecotyfanboy** [comment]
Thank you very much! I'll open some PRs soon then. I would be glad to embed this in the [spectral fitting package](https://github.com/renecotyfanboy/jaxspec) we are developing at IRAP
